<?xml version="1.0" encoding="UTF-8"?>
<Project>
    <Project_Created_Time>2026-08-25 15:08:18</Project_Created_Time>
    <TD_Version>4.6.96021</TD_Version>
    <UCode>00000000</UCode>
    <Name>FPGA_Competition_HDMI</Name>
    <HardWare>
        <Family>EG4</Family>
        <Device>EG4S20BG256</Device>
    </HardWare>
    <Source_Files>
        <Verilog>
            <File>src/display/image_enhance.v</File>
            <File>src/display/vga_timing.v</File>
            <File>src/app/app_scenario.v</File>
            <File>src/audio/tone_gen.v</File>
            <File>src/audio/audio_visual.v</File>
            <File>src/display/color_space.v</File>
            <File>src/display/yuv420_upsample.v</File>
            <File>src/display/image_scaler.v</File>
            <File>src/display/osd_overlay.v</File>
            <File>src/display/transition.v</File>
            <File>src/display/tmds_encoder.v</File>
            <File>src/framebuf/async_fifo.v</File>
            <File>src/interact/beep.v</File>
            <File>src/interact/dual_led.v</File>
            <File>src/interact/key_filter.v</File>
            <File>src/interact/menu_fsm.v</File>
            <File>src/interact/seg_driver.v</File>
            <File>src/interact/sw_filter.v</File>
            <File>src/storage/bmp_parser.v</File>
            <File>src/storage/fat32_scan.v</File>
            <File>src/storage/sd_reader.v</File>
            <File>src/storage/sd_spi.v</File>
            <File>src/storage/vseq_reader.v</File>
            <File>src/storage/vseq_yuv_unpack.v</File>
            <File>src/top/reset_gen.v</File>
            <File>src/audio/hdmi_audio_pack.v</File>
            <File>src/storage/fat32_file_reader.v</File>
            <File>src/storage/bmp_pixel_stream.v</File>
            <File>src/framebuf/framebuffer_writer.v</File>
            <File>src/framebuf/frame_buffer_manager.v</File>
            <File>src/framebuf/line_buffer_pingpong.v</File>
            <File>src/framebuf/line_prefetcher.v</File>
            <File>src/framebuf/sdram_arbiter.v</File>
        </Verilog>
        <ADC_FILE/>
        <SDC_FILE/>
        <CWC_FILE/>
    </Source_Files>
    <TOP_MODULE>
        <LABEL/>
        <MODULE>reset_gen</MODULE>
        <CREATEINDEX>user</CREATEINDEX>
    </TOP_MODULE>
    <Project_Settings>
        <Step_Last_Change>2026-08-31 03:57:00</Step_Last_Change>
        <Current_Step>0</Current_Step>
        <Step_Status>true</Step_Status>
    </Project_Settings>
</Project>
